name: Assistant push
on:
  workflow_dispatch:
  repository_dispatch:
    types: [assistant_push]

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - run: |
          git config user.name "fitlife-assistant"
          git config user.email "fitlife-assistant@users.noreply.github.com"
          git remote set-url origin git@github.com:akshaynalawade701-cyber/FitLife.git
          # TODO: apply edits here (DEXA/UI). Only commit if files changed:
          git add -A
          git diff --cached --quiet || git commit -m "Assistant update"
          git push origin HEAD:main
To trigger without UI clicks (external API):
curl -fsSL -X POST \
  -H "Authorization: Bearer YOUR_PAT" \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/repos/akshaynalawade701-cyber/FitLife/dispatches \
  -d '{"event_type":"assistant_push"}'
