name: Assistant push
on:
  workflow_dispatch:
  repository_dispatch:
    types: [assistant_push]

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }

      - name: Use deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Apply UI/theme edits and cache-bust
        shell: bash
        run: |
          python3 - <<'PY'
          from pathlib import Path
          import re, time

          changed = False

          # 1) Write improved CSS (light/dark via CSS vars)
          css = """\
:root{
  --brand:#07c0a2;
  --bg:#ffffff;
  --text:#0b132b;
  --muted:#475569;
  --card:#ffffff;
  --border:#e2e8f0;
  --elev:0 1px 3px rgba(2,6,23,.06),0 1px 2px rgba(2,6,23,.04);
  --elev-2:0 10px 15px -3px rgba(2,6,23,.08),0 4px 6px -4px rgba(2,6,23,.06);
  --ring:0 0 0 3px color-mix(in srgb, var(--brand) 30%, transparent);
  --btn-text:#ffffff;
  --link:#0ea5a5;
}
[data-theme="dark"]{
  --bg:#0b132b;
  --text:#e5e7eb;
  --muted:#94a3b8;
  --card:#111827;
  --border:#1f2937;
  --elev:0 1px 3px rgba(0,0,0,.3),0 1px 2px rgba(0,0,0,.2);
  --elev-2:0 10px 15px -3px rgba(0,0,0,.35),0 4px 6px -4px rgba(0,0,0,.28);
  --btn-text:#0b132b;
  --link:#22d3ee;
}
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;background:var(--bg);color:var(--text);
  font:400 16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,Inter,Arial,sans-serif;
  text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased
}
a{color:var(--link);text-decoration:none}
a:hover{text-decoration:underline}
.container{max-width:1100px;margin:0 auto;padding:0 16px}
.site-header{
  position:sticky;top:0;z-index:20;backdrop-filter:saturate(150%) blur(6px);
  background:color-mix(in srgb,var(--bg) 80%,transparent);
  border-bottom:1px solid var(--border)
}
.header-inner{display:flex;align-items:center;justify-content:space-between;height:64px}
.brand{display:flex;gap:8px;align-items:center;font-weight:700;color:var(--text)}
.brand-mark{font-size:20px}
.icon-btn{
  appearance:none;border:1px solid var(--border);background:var(--card);color:var(--text);
  border-radius:8px;padding:8px 10px;cursor:pointer;box-shadow:var(--elev)
}
.icon-btn:hover{box-shadow:var(--elev-2)}
.site-nav{display:flex;gap:14px;align-items:center}
.site-nav a{color:var(--text);opacity:.9}
.site-nav a:hover{opacity:1}
.badge{
  display:inline-block;background:color-mix(in srgb,var(--brand) 20%, var(--bg));
  border:1px solid color-mix(in srgb,var(--brand) 35%, var(--border));
  color:var(--text);padding:2px 8px;border-radius:999px;font:600 12px/1 system-ui
}
.hero{padding:48px 0;border-bottom:1px solid var(--border);
  background:linear-gradient(180deg, color-mix(in srgb,var(--brand) 6%, var(--bg)) 0%, var(--bg) 100%)}
.hero-inner{display:grid;grid-template-columns:1.1fr .9fr;gap:32px;align-items:center}
.hero-copy h1{margin:0 0 8px;font-size:40px;line-height:1.15}
.hero-copy p{margin:0 0 20px;color:var(--muted)}
.hero-ctas{display:flex;gap:10px;flex-wrap:wrap}
.hero-card{
  background:var(--card);border:1px solid var(--border);border-radius:16px;
  padding:18px;box-shadow:var(--elev-2);display:flex;gap:12px;justify-content:space-between
}
.stat{display:flex;flex-direction:column;align-items:center;gap:4px}
.stat span{font-weight:800;font-size:22px}
.stat small{color:var(--muted)}
.section{padding:44px 0}
.section.alt{background:color-mix(in srgb,var(--bg) 92%, var(--brand) 8% / 5%)}
.section-header h2{margin:0 0 6px}
.section-header p{margin:0;color:var(--muted)}
.grid{display:grid;gap:16px}
.grid.cols-2{grid-template-columns:repeat(2,1fr)}
.grid.cols-3{grid-template-columns:repeat(3,1fr)}
.grid.cols-4{grid-template-columns:repeat(4,1fr)}
@media (max-width:900px){
  .hero-inner{grid-template-columns:1fr}
  .grid.cols-4{grid-template-columns:1fr 1fr}
}
@media (max-width:640px){
  .grid.cols-3,.grid.cols-2,.grid.cols-4{grid-template-columns:1fr}
}
.card{
  background:var(--card);border:1px solid var(--border);border-radius:12px;
  padding:16px;box-shadow:var(--elev)
}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.row-inline{display:inline-flex;gap:8px;align-items:center}
.muted{color:var(--muted)}
input,select,textarea,button{font:inherit;color:inherit}
input,select,textarea{
  width:100%;padding:10px 12px;border-radius:10px;border:1px solid var(--border);
  background:var(--bg);color:var(--text);outline:none;transition:border-color .15s, box-shadow .15s
}
input:focus,select:focus,textarea:focus{border-color:var(--brand);box-shadow:var(--ring)}
label{display:flex;flex-direction:column;gap:6px}
.btn{
  appearance:none;border:1px solid var(--border);background:var(--card);color:var(--text);
  padding:10px 14px;border-radius:10px;cursor:pointer;box-shadow:var(--elev);transition:transform .05s
}
.btn:hover{box-shadow:var(--elev-2)}
.btn:active{transform:translateY(1px)}
.btn-primary{background:var(--brand);border-color:color-mix(in srgb,var(--brand) 60%, var(--border));color:var(--btn-text)}
.btn-secondary{background:color-mix(in srgb,var(--brand) 18%, var(--bg));border-color:color-mix(in srgb,var(--brand) 45%, var(--border))}
.btn-ghost{background:transparent}
.file-btn{position:relative;overflow:hidden}
.file-btn input[type="file"]{position:absolute;inset:0;opacity:0;cursor:pointer}
.preview-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:10px}
.preview-grid img,.preview-grid video{width:100%;height:120px;object-fit:cover;border-radius:10px;border:1px solid var(--border)}
.annotated-wrap{display:block;max-width:720px;margin:12px auto 0}
.annotated-canvas{width:100%;height:auto;border-radius:12px;border:1px solid var(--border);background:color-mix(in srgb,var(--bg) 96%, var(--brand))}
.results{align-self:start}
.table-wrap{overflow:auto}
.table{width:100%;border-collapse:collapse}
.table th,.table td{padding:10px;border-bottom:1px solid var(--border);text-align:left}
.table th{color:var(--muted);font-weight:600}
.footer-inner{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-top:1px solid var(--border)}
.plan{display:grid;gap:10px}
.quote{border-left:4px solid var(--brand);background:color-mix(in srgb,var(--brand) 6%, var(--card));}
.dexa-card{margin-top:8px;padding:10px;border-radius:10px;background:color-mix(in srgb,var(--brand) 6%, var(--card));border:1px solid color-mix(in srgb,var(--brand) 40%, var(--border))}
.dexa-title{font-weight:700;margin-bottom:6px;color:var(--brand)}
.dexa-row{display:flex;justify-content:space-between;gap:8px;margin:4px 0}
.dexa-row span{color:var(--muted)}
.dexa-row b{color:var(--text)}
.icon-btn:focus,.btn:focus,input:focus,select:focus,textarea:focus{outline:none;box-shadow:var(--ring)}
"""
          css_path = Path('assets/css/styles.css')
          if (not css_path.exists()) or (css_path.read_text(encoding='utf-8') != css):
            css_path.parent.mkdir(parents=True, exist_ok=True)
            css_path.write_text(css, encoding='utf-8')
            changed = True

          # 2) Append theme toggle JS to main.js if missing
          js_snip = """\
(function(){
  try {
    const root = document.documentElement;
    const saved = localStorage.getItem('fitlife_theme');
    if (saved === 'dark') root.setAttribute('data-theme','dark');
    const btn = document.getElementById('theme-toggle');
    if (btn && !btn.__bound) {
      btn.__bound = true;
      btn.addEventListener('click', () => {
        const dark = root.getAttribute('data-theme') === 'dark';
        root.setAttribute('data-theme', dark ? 'light' : 'dark');
        localStorage.setItem('fitlife_theme', dark ? 'light' : 'dark');
      });
    }
  } catch(e) {}
})();
"""
          mjs = Path('assets/js/main.js')
          if mjs.exists():
            cur = mjs.read_text(encoding='utf-8')
            if 'fitlife_theme' not in cur:
              mjs.write_text(cur.rstrip() + "\n" + js_snip, encoding='utf-8')
              changed = True

          # 3) Bump CSS version in index.html to force reload
          idx = Path('index.html')
          if idx.exists():
            html = idx.read_text(encoding='utf-8')
            html2 = re.sub(r'(assets/css/styles\\.css)(\\?v=[^"\\s]+)?', r'\\1?v=11', html)
            if html2 != html:
              idx.write_text(html2, encoding='utf-8')
              changed = True

          print("CHANGED=" + ("1" if changed else "0"))
          PY

      - name: Commit and push if changed
        run: |
          git config user.name "fitlife-assistant"
          git config user.email "fitlife-assistant@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Assistant: UI/theme upgrade + cache-bust"
          git push origin HEAD:main
