name: Assistant push
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config user.name "fitlife-assistant"
          git config user.email "fitlife-assistant@users.noreply.github.com"
          git remote set-url origin git@github.com:akshaynalawade701-cyber/FitLife.git

      - name: Apply changes and push
        run: |
          # (I will edit files in a follow-up run of this workflow)
          git add -A
          git commit -m "Assistant update" || echo "No changes"
          git push origin HEAD:main || true
